sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
before_install:
  - npm install -g hexo-cli
branches:
  only:
    - master # build master branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GN_TOKEN
  keep-history: true
  target_branch: master
  on:
    branch: source
  local-dir: public
